common/models/User.php
<?php
namespace common\models;

use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;

/**
 * User model
 *
 * @property integer $id
 * @property string $username
 * @property string $password_hash
 * @property string $password_reset_token
 * @property string $email
 * @property string $auth_key
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $password write-only password
 */
class User extends ActiveRecord implements IdentityInterface
{
    const STATUS_DELETED = 0;
    const STATUS_ACTIVE = 10;

    public $roles;
    public $password;
    public $imageFile;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%user}}';
    }

    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['username','password'],'string' ],
            [['roles'],'safe'],
            [['email'],'email'],
            [['username','email'],'unique'],
            ['status', 'default', 'value' => self::STATUS_ACTIVE],
            ['status', 'in', 'range' => [self::STATUS_ACTIVE, self::STATUS_DELETED]],
            [['imageFile'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg', 'on'=>'update'],
            [['username','email', 'password', 'roles'], 'required', 'on' => 'create' ],
            [['username','email', 'password'], 'required', 'on' => 'userCreate' ],
            [['username','email', 'roles'], 'required', 'on' => 'adminUpdate'],
            [['username','email'], 'required', 'on' => 'userUpdate']
        ];
    }





        public function upload()
        {
            if($this->validate()){
                $files = scandir(\Yii::getAlias('@frontend') . '/web/images/');
                if(in_array($this->id.'.png',$files)){
                    unlink(\Yii::getAlias('@frontend').'/web/images/'.$this->id.'.png');
                }
                $this->imageFile->saveAs(Yii::getAlias('@frontend') . '/web/images/' .$this->id . '.png');
                return true;
            }
                return false;
        }

    public function setImage($id)
    {
            $files = scandir(\Yii::getAlias('@frontend') . '/web/images/');
            if(in_array($id.'.png',$files)){
                return '/frontend/web/images/'.$id . '.png';
            }
                return '/frontend/web/images/not-available.png';
    }

    /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        return static::findOne(['id' => $id, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        return static::findOne(['username' => $username, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * Finds user by password reset token
     *
     * @param string $token password reset token
     * @return static|null
     */
    public static function findByPasswordResetToken($token)
    {
        if (!static::isPasswordResetTokenValid($token)) {
            return null;
        }

        return static::findOne([
            'password_reset_token' => $token,
            'status' => self::STATUS_ACTIVE,
        ]);
    }

    /**
     * Finds out if password reset token is valid
     *
     * @param string $token password reset token
     * @return bool
     */
    public static function isPasswordResetTokenValid($token)
    {
        if (empty($token)) {
            return false;
        }

        $timestamp = (int) substr($token, strrpos($token, '_') + 1);
        $expire = Yii::$app->params['user.passwordResetTokenExpire'];
        return $timestamp + $expire >= time();
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return bool if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return Yii::$app->security->validatePassword($password, $this->password_hash);
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password_hash = Yii::$app->security->generatePasswordHash($password);
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = Yii::$app->security->generateRandomString();
    }

    /**
     * Generates new password reset token
     */
    public function generatePasswordResetToken()
    {
        $this->password_reset_token = Yii::$app->security->generateRandomString() . '_' . time();
    }

    /**
     * Removes password reset token
     */
    public function removePasswordResetToken()
    {
        $this->password_reset_token = null;
    }

    public function getUserRoles()
    {
        return $this->hasMany(UserRoles::className(), ['user_id' => 'id']);
    }

    public function getRoles()
    {
        return $this->hasMany(Role::className(), ['id' => 'role_id'])->via('userRoles');
    }

    public function getSendings($id){
        return $this->hasOne(Message::className(), ['sending_id' => 'id'])->where(['recipient_id'=>$id]);
    }

    public function getRecipients($id){
        return $this->hasOne(Message::className(), ['recipient_id' => 'id'])->where(['sending_id'=>$id]);
    }
}

backend/controllers/UserController.php
<?php

namespace backend\controllers;

use common\models\UserRoles;
use Yii;
use common\models\User;
use backend\models\UserSearch;
use yii\helpers\ArrayHelper;
use yii\web\NotFoundHttpException;
use zxbodya\yii2\galleryManager\GalleryManagerAction;


/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends SiteController
{
    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'galleryApi' => [
                'class' => GalleryManagerAction::className(),
                // mappings between type names and model classes (should be the same as in behaviour)
                'types' => [
                    'user' => User::className()
                ]
            ],
        ];
    }
    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new User();
        $model->scenario = 'create';
        if ($model->load(Yii::$app->request->post())) {
            $model->setPassword($model->password);
            $model->generateAuthKey();
            if($model->save()){
                foreach ($model->roles as $role){
                    $user_role = new UserRoles();
                    $user_role->user_id = $model->id;
                    $user_role->role_id = $role;
                    $user_role->save();
                }
                return $this->redirect(['view', 'id' => $model->id]);
            }else {
                return $this->render('create', ['model' => $model]);
            }
        } else {
            return $this->render('create', [ 'model' => $model]);
        }
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $model->scenario = 'adminUpdate';
        $password = $model->password_hash;
        $roles = ArrayHelper::getColumn($model->getRoles()->asArray()->all(), 'id');
        if ($model->load(Yii::$app->request->post())) {
            if(!empty($model->password_hash)) {
                $model->save();
                if(!empty($model->roles)){
                    $this->Roles($model->roles, $model->id);
                } else {
                    $this->Roles($roles, $model->id);
                }

                return $this->redirect(['view', 'id' => $model->id]);
            } else{
                    $model->password_hash = $password;
                    $model->save();
                    if(!empty($model->roles)){

                        $this->Roles($model->roles, $model->id);
                    } else {
                        $this->Roles($roles, $model->id);
                    }
                }

                return $this->redirect(['view', 'id' => $model->id]);

        } else {
            $model->password_hash = '';
            $model->roles = $model->findOne($id)->getRoles()->all();
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

protected function Roles($roles, $id){
    UserRoles::deleteAll(['user_id'=>$id]);
    foreach ($roles as $role){
        $user_role = new UserRoles();
        $user_role->user_id = $id;
        $user_role->role_id = $role;
        $user_role->save();
    }
}
    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        UserRoles::deleteAll(['user_id'=>$id]);
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
           return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/controllers/UserController.php
<?php

namespace frontend\controllers;

use common\models\Files;
use common\models\Message;
use Yii;
use common\models\User;
use frontend\models\UserSearch;
use yii\helpers\Json;
use yii\web\NotFoundHttpException;
use yii\web\UploadedFile;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends SiteController
{
    /**
     * @inheritdoc
     */


    /**
     * Lists all User models.
     * @return mixed
     */
    private $count = 0;

    public function actionIndex()
    {
        $messages = '';
        $recipientId = 0;
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $id = yii::$app->user->id;
        $count = Message::find()
            ->where(['recipient_id' => $id, 'status' => 0])
            ->count();
        if (Yii::$app->request->get('user')) {
            $recipient_id = Yii::$app->request->get('user');
            $userIds = array_keys($searchModel->find()->indexBy('id')->asArray()->all());
            $sending_id = yii::$app->user->id;
            if (in_array($recipient_id, $userIds)) {
                $messages1 = $searchModel->findOne($sending_id)->getSendings($recipient_id)->indexBy('id')->all();
                $messages2 = $searchModel->findOne($sending_id)->getRecipients($recipient_id)->indexBy('id')->all();
                $messages = $messages1 + $messages2;
                ksort($messages);
                $recipientId = array_keys($searchModel->findOne($sending_id)->getRecipients($recipient_id)->select('id')->indexBy('id')->asArray()->all());
            }
        }
        return $this->render('index', compact(
            'searchModel', 'dataProvider', 'count',
            'messages', 'recipientId'
        ));
    }

    public function actionFileUpload()
    {
      /*  $model = new Message();
        if ($model->load(Yii::$app->request->post())) {
                $files = new Files();
                $files->user_id = $model->id;
                $files->name = "{$model->created_at}.{$model->filesUpload->extension}";
                $files->type = $model->filesUpload->type;
                $files->size = $model->filesUpload->size;
                $files->save();
                return json_encode(['success' => true]);
            }*/
        }


    public function actionSendMessages()
    {
        $model = new Message();
        $model->scenario = 'message';
        if ($model->load(Yii::$app->request->post())) {
            if (User::findOne(['id' => $model->sending_id]) && User::findOne(['id' => $model->recipient_id])) {
                $model->save();
                if ($model->type && $model->type == 'files') {
                    if(isset($_FILES)) {
                        print_r($_FILES);
                    }
                //   $model->uploadFile(Yii::$app->request->post('files'));

                   // return $model->insertFile(Yii::$app->request->post('msgFiles'));
                }
                return json_encode(["message" => 'sent', "id" => $model->id]);
            }
            return $this->redirect('index');
        }
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new User();
        $model->scenario = 'userCreate';
        if ($model->load(Yii::$app->request->post())) {
            $model->setPassword($model->password);
            $model->generateAuthKey();

            if ($model->save()) {
                if (Yii::$app->getUser()->login($model)) {
                    return $this->goHome();
                }
            } else {
                return $this->render('create', ['model' => $model]);
            }
        } else {
            return $this->render('create', ['model' => $model]);
        }
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */

    public function actionUpdate()
    {
        $id = \Yii::$app->user->id;
        $model = $this->findModel($id);
        $model->scenario = 'userUpdate';
        $password = $model->password_hash;

        if ($model->load(Yii::$app->request->post())) {
            if (empty($model->password)) {
                $model->setPassword($password);
            } else {
                $model->setPassword($model->password);
            }
            $model->imageFile = UploadedFile::getInstance($model, 'imageFile');
            if (!empty($model->imageFile)) {
                $model->upload();
            }
            $model->save();
            return $this->redirect('index');
        } else {
            $model->password = '';
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }


    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete()
    {
        if (Yii::$app->request->post('id')) {

            $id = Yii::$app->request->post('id');
            Message::findOne($id)->delete();
        }
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

}

frontend/views/user/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\User */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-form">

    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>

    <?= $form->field($model, 'username')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'password')->textInput() ?>

    <?php if(!$model->isNewRecord){
        echo $form->field($model, 'imageFile')->fileInput(['accept' => 'image/*']);
    } ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/user/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\User */

$this->title = 'Create User';
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/user/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use kartik\file\FileInput;
use yii\helpers\Url;
/* @var $this yii\web\View */
/* @var $searchModel frontend\models\UserSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = yii::$app->user->identity->username;
$this->params['breadcrumbs'][] = $this->title;
?>

    <div class="container">
        <div class="col-lg-4">
            <div>

                <?= Html::a(Html::img($searchModel->setImage(yii::$app->user->identity->id), [
                    'alt' => 'My logo',
                    'class' => 'img-circle',
                    'width' => "100",
                    'height' => "60"
                ]), ['update']) ?>
                <h6><?= yii::$app->user->identity->username ?> <div class="count" ><?= $count ?></div></h6>
            </div>
            <?= GridView::widget([
                'dataProvider' => $dataProvider,
                'filterModel' => $searchModel,
                'columns' => [
                    [
                        'attribute'=> '',
                        'filter' => \kartik\select2\Select2::widget([
                            'model' => $searchModel,
                            'attribute' => 'username',
                            'data' => \yii\helpers\ArrayHelper::map(\common\models\User::find()->all(), 'username', 'username' ),
                            'options' => ['placeholder' => 'Users...'],
                            'pluginOptions' => [
                                'allowClear' => true,
                            ],
                        ]),
                        'format'=> 'html',
                        'value' => function($dataProvider, $count){
                            $s = '';
                            if($dataProvider->id !== yii::$app->user->id){
                                $s.= '<li>';
                                $s.= Html::a( $dataProvider->username, $url = '/user/'.$dataProvider->id, $options = [] );
                                $s.='</li>';
                            }
                            return $s;
                        }
                    ]
                ],
            ]); ?>

        </div>
        <div class="col-lg-8">  <?php if(!empty(Yii::$app->request->get('user'))):
            $id = $_GET['user'];
            $user = $searchModel->findOne($id);
                if(!empty($user)):
            ?>
                <div class="row">
                    <div style="margin-top: 10%">
                        <div class="col-lg-4">
                            <?= Html::img($searchModel->setImage($id), [
                                'alt' => 'My logo',
                                'class' => 'img-circle',
                                'width' => "200",
                                'height' => "150"
                            ]) ?>
                        </div>
                        <div class="col-lg-5">
                            <l><?= $user->username ?></l><br>
                            <l><?= $user->email ?></l>
                        </div>
                        <div class="col-lg-3">
                            <button id="open-message" class="btn">message</button>
                        </div>
                    </div>

                </div>
                <div class="row divMessage">
                    <button id="x" class="btn">X</button>
                    <div class="col-md-12 col-lg-12 col-sm-12">
                        <?= $this->render('messages', compact(
                            'messages', 'recipientId','id'
                        )) ?>
                    </iew') ?>
                    <div class="input-message">
                        <div class="col-md-11 col-lg-11 col-sm-11">
                          <textarea id = 'text' type="text" wrap="soft"  ></textarea>
                            <input id = 'recipient_id' type="hidden" value="<?= $id ?>">
                            <input id = 'sending_id' type="hidden" value="<?= yii::$app->user->identity->id ?>">
                        </div>

                        <div class="col-md-1 col-lg-1 col-sm-1 fileInput" id="fileUpload" >
                            <div style="width: 25px; margin-top: 40%;"><span  class="glyphicon glyphicon-paperclip"></span></div>
                        </div>
                    </div>
                </div>
            </div>

                                <!--    data-toggle="modal" data-target="#exampleModalLong"-->
            <div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLongTitle">File input</h5>
                            <button type="button" class="close fileinput-remove" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <input type="hidden" value="<?= $id ?>">
                            <input type="file" id="fileToUpload" multiple="multiple" name="files[]" />
                            <?php /*FileInput::widget([
                                'attribute' => 'filesUpload',
                                'model' => new \common\models\Message(),
                                'options'=>[
                                    'multiple'=>true
                                ],
                                'pluginOptions' => [
                                    'showPreview' => true ,
                                    'showCaption' => false,
                                    'showRemove' => true,
                                    'showUpload' => true,
                                    'uploadUrl' => Url::to(['/user/file-upload']),
                                    'uploadExtraData' => [
                                        "Message[recipient_id]"=> $id,
                                        "Message[status]" => 0,
                                        "Message[sending_id]"=> yii::$app->user->identity->id,
                                        "Message[type]"=>"files",
                                    ],
                                    'maxFileCount' => 10
                                ]
                            ]);*/?>
                        </div>
                    </div>
                </div>
            </div>
        <?php endif; endif; ?>
        </div>
    </div>

frontend/views/user/messages.php
<?php /* @var $recipientId[] common\models\Message */ ?>
<?php /* @var $messages common\models\Message */ ?>
<?php
    use yii\helpers\Html;
?>
<div id= "messages">
     <?php
        if(!empty($messages)){
            foreach($messages as $message){
                if(in_array(  $message->id, $recipientId )){
                     $message->status = 1;
                     $message->save();
    ?>
                    <div class="messigeDiv right">
                        <?php if($message->type == 'text'){ ?>
                    <p class="getMessage" title="<?= date("Y-M-d H:i:s", $message->created_at) ?>"><?= $message->message ?></p>
                        <?php } else {
                            $url = '/frontend/web/files/'.$message->sending_id."/".$message->recipient_id.'/'.$message->id.'.'.$message->type;
                            ?>
                            <p class="getMessage" title="<?= date("Y-M-d H:i:s", $message->created_at) ?>"><?= Html::img($url) ?></p>
                        <?php } ?>
                    </div>
            <?php }else{ ?>
        <div class="messigeDiv left" id = "id<?= $message->id ?>">
            <?php if($message->type == 'text'){ ?>
                <p class="sendMessage" title="<?= date("Y-M-d H:i:s", $message->created_at) ?>">
                    <button onClick='delet(<?= $message->id ?>)' class = "del">x</button>
                    <?= $message->message ?>
                </p>
            <?php } else {
                $url = '/frontend/web/files/'.$message->sending_id."/".$message->recipient_id.'/'.$message->id.'.'.$message->type;
                ?>
                <p class="sendMessage" title="<?= date("Y-M-d H:i:s", $message->created_at) ?>">
                    <button onClick='delet(<?= $message->id ?>)' class = "del">x</button>
                    <?php //Html::img($url, ['width'=>100, 'heigth' =>100]) ?></p>
                </p>
            <?php } ?>
        </div>
    <?php       }
            }
        }
    ?>
</div>

frontend/views/user/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\User */

$this->title = 'Update User: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="user-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>